#!/bin/bash
WEBSITE=$(echo -e "twitch\nyoutube" | dmenu -p Firefox)
echo $WEBSITE

if [ "$WEBSITE" == "youtube" ]; then
	WEBSITE="https://www.youtube.com"
elif [ "$WEBSITE" == "twitch" ]; then
	WEBSITE="https://www.twitch.tv"
fi

if [ "$WEBSITE" != "" ]; then
	echo $WEBSITE;
	firefox --new-window $WEBSITE;
fi
