#!/bin/bash
WEBSITE=$(echo -e "reddit\ntwitch\nyoutube" | dmenu -p Firefox)
echo $WEBSITE

if [ "$WEBSITE" == "youtube" ]; then
	WEBSITE="https://www.youtube.com"
elif [ "$WEBSITE" == "twitch" ]; then
	WEBSITE="https://www.twitch.tv"
elif [ "$WEBSITE" == "reddit" ]; then
	WEBSITE="https://www.reddit.com"
fi

if [ "$WEBSITE" != "" ]; then
	echo $WEBSITE;
	firefox --new-window $WEBSITE;
fi
