#!/bin/bash

WEBSITE=$(echo -e "youtube\ntwitch\nreddit\n/g/" | dmenu -p 'Website')

BROWSER='firefox';

echo $WEBSITE

if [ "$WEBSITE" == "youtube" ]; then
	WEBSITE="https://www.youtube.com"
elif [ "$WEBSITE" == "twitch" ]; then
	BROWSER="chromium";
	WEBSITE="https://www.twitch.tv"
elif [ "$WEBSITE" == "reddit" ]; then
	WEBSITE="https://www.reddit.com"
elif [ "$WEBSITE" == "/g/" ]; then
	WEBSITE="https://www.4chan.org/g/catalog";
fi

if [ "$WEBSITE" != "" ]; then
	$BROWSER --new-window $WEBSITE;
fi
