#!/bin/bash

WEBSITE=$(echo -e "youtube\ntwitch\nreddit\n/g/\nspotify\namazon\ngmail\nindeed" | dmenu -p 'Website')

BROWSER='firefox';

echo $WEBSITE

if [ "$WEBSITE" == "youtube" ]; then
	WEBSITE="https://www.youtube.com"
elif [ "$WEBSITE" == "twitch" ]; then
	BROWSER="chromium";
	WEBSITE="https://www.twitch.tv"
elif [ "$WEBSITE" == "reddit" ]; then
	WEBSITE="https://www.reddit.com"
elif [ "$WEBSITE" == "/g/" ]; then
	WEBSITE="https://www.4chan.org/g/catalog";
elif [ "$WEBSITE" == "spotify" ]; then
	WEBSITE="https://open.spotify.com/";
elif [ "$WEBSITE" == "amazon" ]; then
	WEBSITE="https://www.amazon.com/";
elif [ "$WEBSITE" == "gmail" ]; then
	WEBSITE="https://www.gmail.com/";
elif [ "$WEBSITE" == "indeed" ]; then
	WEBSITE="https://www.indeed.com";
fi

if [ "$WEBSITE" != "" ]; then
	$BROWSER --new-window $WEBSITE;
fi
